include theos/makefiles/common.mk
export GO_EASY_ON_ME=1
export OWNED=1; 
TWEAK_NAME = CallNow
CallNow_FILES = Tweak.xm
CallNow_FRAMEWORKS = UIKit CoreGraphics
CallNow_LDFLAGS = -lactivator
include $(THEOS_MAKE_PATH)/tweak.mk
