include theos/makefiles/common.mk
export GO_EASY_ON_ME=1
TWEAK_NAME = PlayingBot
PlayingBot_FILES = Tweak.xm
PlayingBot_FRAMEWORKS = UIKit CoreGraphics QuartzCore MediaPlayer
#SUBPROJECTS = playingbotsettings
include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
