include theos/makefiles/common.mk

TWEAK_NAME = StartDial
StartDial_FILES = Tweak.xm
StartDial_FRAMEWORKS = UIKit
SUBPROJECTS = StartDialPreferences

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
