include theos/makefiles/common.mk

TWEAK_NAME = VolumeTasking
VolumeTasking_FILES = Tweak.xm
VolumeTasking_FRAMEWORKS = UIKit CoreGraphics
VolumeTasking_LDFLAGS = -lactivator
include $(THEOS_MAKE_PATH)/tweak.mk
